version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - ../mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express-koradi:
    container_name: mongo-express-koradi
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
    depends_on: [mongo]

  server:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && node src/server.js"
    volumes:
      - ../server:/app
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - ORG_NAME=${ORG_NAME}
      - GOAL_MIN=${GOAL_MIN}
      - GOAL_MAX=${GOAL_MAX}
      - BINGO_PRICE=${BINGO_PRICE}
    ports: ["4000:4000"]
    depends_on: [mongo]

  web:
    image: nginx:alpine
    depends_on: [server]
    volumes:
      - ../client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports: ["80:80"]

# volumes:
#   mongo-data:
